service: flask-app

provider:
  name: aws
  runtime: python3.11  # Ensure this matches AWS Lambda supported versions
  region: ap-south-1  # Change if needed
  environment:
    DATABASE_URL: postgresql://postgres:leomessiten@rdspg172.cpyacgkokb25.ap-south-1.rds.amazonaws.com:5432/postgres

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app  # Ensure this matches your Flask app instance
  pythonRequirements:
    dockerizePip: true
